# 项目相关配置
mproject:
  # 名称
  name: MProject
  # 版本
  version: 1.0
  # 版权年份
  copyrightYear: 2020
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/mproject/uploadPath，Linux配置 /home/mproject/uploadPath）
  #profile: /home/mproject/uploadPath
  profile: D:/mproject/uploadPath
  
  # 获取ip地址开关
  addressEnabled: true

  staticUploadPrefix: /static/upload/

  staticUpload: /static/upload/**

  uploadFolderPath: D:/idea-workspace/mproject/static/upload/
  #uploadFolderPath: home/mproject/static/upload/

  imgServer: http://122.112.164.217:8888/teamProject/
  #用户默认图标
  userImg: user.jpg
  #项目默认图标
  projectImg: project.png


  #downloadServer: http://120.27.62.173:8888
  downloadServer: http://122.112.164.217:8888

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8888
#  servlet:
#    # 应用的访问路径
#    context-path: /api/
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: debug

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      #url: jdbc:mysql://139.199.229.215:3306/teamwork?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&tinyInt1isBit=false
      url: jdbc:mysql://122.112.164.217:3306/teamwork?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&tinyInt1isBit=false
      username: teamwork
      password: Admin@123!
      #password: P@ssWord8.0
  #Redis
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 密码
    password: fZxm2gSUeR9VfXzZlk9GemUw2
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms


    # MyBatis
    #mybatis:
    # 搜索指定包别名
    #typeAliasesPackage: com.ruoyi.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    #mapperLocations: classpath:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    #configLocation: classpath:mybatis/mybatis-config.xml
  mvc:
    #出现错误时, 直接抛出异常
    throw-exception-if-no-handler-found: true
  resources:
    #不要为我们工程中的资源文件建立映射
    add-mappings: false


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  mapper-locations: classpath:mybatis/**/*Mapper.xml
  type-aliases-package: com.mproject.*.**.domain
  global-config:
    refresh: true # 刷新xml文件
    db-config:
      logic-delete-value: 1 #默认值1
      logic-not-delete-value: 0 #默认值0
      #数据库类型
      db-type: mysql


# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# JWT
jwt:
  header: Authorization
  secret: mySecret
  #token有效期时间（分钟）
  expiration: 120
  tokenHead: "Bearer "

#要放行的url
custom:
  ignored-role-path: /favicon.ico, /teamwork/login, /index/index/refreshAccessToken, /project/login/getCaptcha, /project/login/register, /project/task/_downloadTemplate, /project/task/uploadFile,
      /project/department_member/_downloadTemplate, /project/department_member/uploadFile, /common/download, /project/index, /common/image, /imserver, /index/index/bindClientId, 
      /project/login/_out, /project/index/systemConfig